cc_library(
    name = "libserialport",
    srcs = [
        "config.h",
        "libserialport_internal.h",
        "linux.c",
        "linux_termios.c",
        "linux_termios.h",
        "serialport.c",
        "timing.c",
    ],
    hdrs = [
        "config.h",
        "libserialport.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
